export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const ALL_RECOMMENDED_PRODUCTS_REQUEST = "ALL_RECOMMENDED_PRODUCTS_REQUEST";
export const ALL_RECOMMENDED_PRODUCTS_SUCCESS = "ALL_RECOMMENDED_PRODUCTS_SUCCESS";
export const ALL_RECOMMENDED_PRODUCTS_FAIL = "ALL_RECOMMENDED_PRODUCTS_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const GET_FEATURED_REQUEST = "GET_FEATURED_REQUEST";
export const GET_FEATURED_SUCCESS = "GET_FEATURED_SUCCESS";
export const GET_FEATURED_FAIL = "GET_FEATURED_FAIL";

export const GET_ALL_PRODUCT_CATEGORIES_REQUEST =
  "GET_ALL_PRODUCT_CATEGORIES_REQUEST";
export const GET_ALL_PRODUCT_CATEGORIES_SUCCESS =
  "GET_ALL_PRODUCT_CATEGORIES_SUCCESS";
export const GET_ALL_PRODUCT_CATEGORIES_FAIL =
  "GET_ALL_PRODUCT_CATEGORIES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PAGE_LIMIT = 8;
